[package]
name = "galaxies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.4.1"
glam = "0.27.0"
quad-rand = "*"
